name: Deploy API to CGP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/Checkout@v3

      - name: Set up PHP
        uses: shivammatur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Copy files to Server
        uses: appleboy/scp-action@v0.2.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "./*"
          target: "/var/www/html/fana-api"

      - name: Restart Apache
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script:
            sudo systemclt restart apache2

